config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :jobs

  resources :companies

  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :jobs

  validates :name, uniqueness: {}
end

app/models/company.rb
class Company < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :jobs, dependent: :destroy

  validates :name, :location, :mail, :phone, presence: true

  validates :name, uniqueness: {}

  def premium?
    jobs.count >= 5
  end
end

app/models/job.rb
class Job < ApplicationRecord
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  belongs_to :company
  belongs_to :category

  validates :title, :location, :description, :category, :company, presence: true

  def expired?
    created_at < 90.days.ago
  end

  def recent?
    created_at > 5.days.ago
  end

  def slug_candidates
    [
      %i[title company_id]
    ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Tipo de flash para o bootstrap 4.1
  add_flash_types :primary,
                  :secondary,
                  :success,
                  :danger,
                  :warning,
                  :info,
                  :light,
                  :dark
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_categories, only: %i[show
                                          edit
                                          update]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category, success: 'Categoria cadastrada com sucesso :)'
    else
      flash[:warning] = 'Essa categoria já existe.'
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to @category
    else
      flash.now[:error] = 'Erro ao salvar :('
      render :edit, danger: 'Não foi possível atualizar a vaga'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_categories
    @category = Category.friendly.find(params[:id])
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_companies, only: %i[show
                                         edit
                                         update]
  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to @company, success: 'Empresa cadastrada com sucesso :)'
    else
      flash[:warning] = 'Essa empresa já existe.'
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @company.update(company_params)
      redirect_to @company
    else
      flash.now[:error] = 'Erro ao salvar :('
      render :edit
    end
  end

  private

  def company_params
    params.require(:company).permit(:name, :location, :mail, :phone)
  end

  def set_companies
    @company = Company.friendly.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @companies = Company.all
    @categories = Category.all
    @jobs = Job.all
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[show
                                   edit
                                   update]
  before_action :set_references, only: %i[new
                                          update
                                          create
                                          edit]

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to @job, success: 'Vaga cadastrada com sucesso :)'
    else
      flash[:warning] = 'Verifique se a categoria e a empresa estão selecionadas.'
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @job.update(job_params)
      redirect_to @job, success: 'Vaga alterada com sucesso :)'
    else
      flash[:warning] = 'Verifique se a categoria e a empresa estão selecionadas.'
      render :edit
    end
  end

  def destroy
    @job = Job.friendly.find(params[:id])
    @job.destroy

    redirect_to root_path, danger: 'Vaga excluída com sucesso :('
  end

  private

  def job_params
    params.require(:job).permit(:title,
                                :location,
                                :category_id,
                                :company_id,
                                :description,
                                :featured)
  end

  def set_job
    @job = Job.friendly.find(params[:id])
  end

  def set_references
    @companies = Company.all
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Padronizando data PT-BR
  def person_date(date)
    date.strftime('%d/%m/%Y')
  end
end

app/views/categories/_form.html.erb
<div class="card">
	<% if current_page?(new_category_path) %>
		<div class="card-header">
			<strong>Criar nova categoria</strong>
		</div>
	<% else %>
		<div class="card-header">
			<strong>Editar vaga</strong>
		</div>
	<% end %>

	<div class="card-body" align="center">
			<%= form_for @category do |f| %>
				<div class="row col-md-6 mb-3">
					<strong>
						<%= f.label :name do %>
						<i class="fa fa-user"></i>
						Nome
						<% end %>
					</strong>
					<%= f.text_field :name, class:"form-control", required: true, autofocus:true %>
				</div>

				<% if @category.new_record?  %>
				<div class="col-md-6 mb-3">
					<%= button_tag type: 'submit', class: "form-control btn btn-success" do %>
						<i class="fa fa-plus"></i>
						CRIAR
					<% end %><br><br>
				</div>
				<% else %>
					<div class="col-md-6 mb-3">
						<%= button_tag type: 'submit', class: "form-control btn btn-warning" do %>
							<i class="fa fa-edit"></i>
							ATUALIZAR VAGA
						<% end %><br><br>
					</div>
				<% end %>

				<%= link_to root_path, class: 'btn btn-primary' do %>
					<i class="fa fa-arrow-left"></i>
					VOLTAR
				<% end %>
			<% end %>
	</div>
</div>

app/views/categories/edit.html.erb
<%= render partial: 'form', locals: {submit_button: 'Atualizar Categoria' } %>

app/views/categories/new.html.erb
<%= render partial: 'form', locals: {submit_button: 'Criar Categoria' }%>

app/views/categories/show.html.erb
<% if @category.jobs.exists?  %>

  <h3>Lista de vagas <strong><%= @category.name %></strong></h3>
    <div class="row">
      <%= render(@category.jobs) %>
    </div>

    <div class="row col-md-6 mb-3" align="center">
      <%= link_to root_path, class: "btn btn-primary" do %>
        <i class="fa fa-arrow-left"></i>
        VOLTAR
      <% end %>
    </div>
<% else %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <i class="far fa-frown"></i> Categoria <strong><%= @category.name %></strong> não possui vagas.
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
  </div>
  <%= link_to new_job_path, class: "btn btn-success" do %>
    <i class="fa fa-plus"></i>
    Criar vaga
  <% end %><br><br>

  <div class="row col-md-6 mb-3" align="center">
    <%= link_to root_path, class: "btn btn-primary" do %>
      <i class="fa fa-arrow-left"></i>
      VOLTAR
    <% end %>
  </div>
<% end %>

app/views/companies/_form.html.erb
<div class="card">
	<% if current_page?(new_company_path) %>
	<div class="card-header">
		<strong>Criar nova empresa</strong>
	</div>
	<% else %>
		<div class="card-header">
			<strong>Editar vaga</strong>
		</div>
	<% end %>

	<div class="card-body" align="center">
		<%= form_for @company do |f| %>
		<div class="row col-md-6 mb-3">
			<strong>
				<%= f.label :name do %>
				<i class="fa fa-user"></i>
				Nome
				<% end %>
			</strong>
			<%= f.text_field :name, class: "form-control", required: true, autofocus: true %>
		</div>

		<div class="row col-md-6 mb-3">
			<strong>
				<%= f.label :location do %>
				<i class="fas fa-map-marker-alt"></i>
				Localização
				<% end %>
			</strong>
			<%= f.text_field :location, class: "form-control", required: true %>
		</div>

		<div class="row col-md-6 mb-3">
			<strong>
				<%= f.label :mail do %>
				<i class="fa fa-envelope"></i>
				E-mail
				<% end %>
			</strong>
			<%= f.email_field :mail, class: "form-control", required: true %>
		</div>

		<div class="row col-md-6 mb-3">
			<strong>
				<%= f.label :phone, "Nome" do %>
				<i class="fa fa-phone"></i>
				Telefone
				<% end %>
			</strong>
			<%= f.text_field :phone, class: "form-control phone", required: true %>
		</div>

		<% if @company.new_record?  %>
		<div class="col-md-6 mb-3">
			<%= button_tag type: 'submit', class: "form-control btn btn-success" do %>
				<i class="fa fa-plus"></i>
				CRIAR
			<% end %><br><br>
		</div>
		<% else %>
			<div class="col-md-6 mb-3">
				<%= button_tag type: 'submit', class: "form-control btn btn-warning" do %>
					<i class="fa fa-edit"></i>
					ATUALIZAR VAGA
				<% end %><br><br>
			</div>
		<% end %>

		<%= link_to root_path, class: 'btn btn-primary' do %>
			<i class="fa fa-arrow-left"></i>
			VOLTAR
		<% end %>
	<% end %>
	</div>
</div>

app/views/companies/edit.html.erb
<%= render partial: 'form', locals: {submit_button: 'Atualizar Empresa'} %>    

app/views/companies/new.html.erb
<%= render partial: 'form', locals: {submit_button: 'Criar empresa'} %>    

app/views/companies/show.html.erb
<% if @company.jobs.exists?  %>

  <h3>Lista de vagas <strong><%= @company.name %></strong></h3>
    <div class="row">
      <%= render(@company.jobs) %>
    </div>

    <div class="row col-md-6 mb-3" align="center">
      <%= link_to root_path, class: "btn btn-primary" do %>
        <i class="fa fa-arrow-left"></i>
        VOLTAR
      <% end %>
    </div>
<% else %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <i class="far fa-frown"></i> Empresa <strong><%= @company.name %></strong> não possui nenhuma vaga.
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
  </div>
  <%= link_to new_job_path, class: "btn btn-success" do %>
    <i class="fa fa-plus"></i>
    Criar vaga
  <% end %><br><br>

  <div class="row col-md-6 mb-3" align="center">
    <%= link_to root_path, class: "btn btn-primary" do %>
      <i class="fa fa-arrow-left"></i>
      VOLTAR
    <% end %>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="container">
  <div class=jumbotrom align="center">
    <h1>Afim de uma vaga?</h1>
    <p> Encontre a sua vaga na Job GO!</p>
    <%= link_to 'Criar Vaga', new_job_path, class: 'btn btn-primary' %>
  </div>
</div>
<br>
<div class="container">
  <% unless @jobs.exists? %>
  <div class="alert alert-warning" role="alert" align="center">
    <i class="far fa-frown"></i> Nenhuma vaga disponível
  </div>
  <% else %>
  <div class="row">
    <% @jobs.each do |job| %>
    <% unless job.expired? %>
    <div class="col-md-4">
      <div class="card-deck mb-3 text-center">
          <div class="card mb-4 box-shadow">
            <div class="card-header">
              <h4 class="my-0 font-weight-normal"><%= job.title %></h4>
            </div>
            <div class="card-body">
              <h3 class="card-title pricing-card-title"><small class="text-muted"><i class="fas fa-clipboard-list"></i> <%= job.description %></small></h3>
              <ul class="list-unstyled mt-3 mb-4">
                <li><i class="fas fa-map-marker-alt"></i> <%= job.location %></li>
                <% if job.recent? %>
                  <strong>Novidade</strong>
                  <li><i class="far fa-calendar-alt"></i> Vaga recente: <%= person_date job.created_at %></li>
                <% else %>
                  <li>
                    <i class="far fa-calendar-alt"></i> Vaga com mais de 5 dias: <%= person_date job.created_at %>
                  </li>
                <% end %>
                <li><i class="fa fa-tag"></i> Categoria: <%= job.category.name %></li>
                <li><i class="far fa-building"></i> Empresa: <%= job.company.name %><li>
                <% if job.featured? %>
                <li><i class="fa fa-star fa-2x text-warning"></i></li>
                <% else  %>
                <li><i class="fa fa-briefcase fa-2x text-primary"></i></li>
                <% end %>
              </ul>
              <%= link_to job_path(job), class: "btn btn-outline-success" do %>
                <i class="fas fa-binoculars"></i>
                VER DETALHES
              <% end %>
              <br>
              <br>
              <%= link_to edit_job_path(job), class: "btn btn-outline-warning" do %>
                <i class="fa fa-edit"></i>
                EDITAR
              <% end %>
              <%= link_to job_path(job), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Você tem certeza que deseja excluir essa vaga? :|" } do %>
                <i class="far fa-trash-alt"></i>
                DELETAR
              <% end %>
            </div>
          </div>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
  <% end %>
</div>
  <div class="jumbotron" align="center">
    <div class="container">
      <i class="far fa-building fa-4x"></i>
      <h1>Cadastre a sua empresa</h1>
      <p>
        Seja o nosso parceiro, os melhores profissionais
        estão a um clique de encontrar a sua vaga.
        Com apenas algumas informações a sua empresa
        estará pronta para o JobGO!
      </p>
      <p>
        <%= link_to 'Criar Empresa', new_company_path, class: "btn btn-success" %></a>
      </p>
      <p align="center">Abaixo a lista das empresas participantes!</p>

      <% unless @companies.exists? %>
      <div class="alert alert-warning" role="alert" align="center">
        <i class="far fa-frown"></i> Nenhuma empresa cadastrada
      </div>
      <% else %>
      <div class="row">
        <% @companies.each do |company| %>
        <div class="col-md-4">
          <div class="card-deck mb-3 text-center">
              <div class="card mb-4 style="max-width: 18rem;"">
                <div class="card-header">
                  <h4 class="my-0 font-weight-normal"><%= company.name %></h4>
                </div>
                <div class="card-body text-dark">
                  <h4 class="card-title pricing-card-title">
                    <small class="text-muted"><i class="fa fa-envelope"></i>
                      <%= company.mail %>
                    </small>
                  </h4>
                  <h4 class="card-title pricing-card-title">
                    <small class="text-muted">
                      <i class="fa fa-phone"></i>  <%= company.phone %>
                    </small>
                  </h4>
                  <h4 class="card-title pricing-card-title">
                    <small class="text-muted">
                      <i class="fa fa-map-marker-alt"></i>
                      <%= company.location %>
                    </small>
                  </h4>
                  <ul class="list-unstyled mt-3 mb-4">
                    <li>
                    <% if company.premium? %>
                      <strong>Premium</strong>
                      <i class="fa fa-star"></i>
                    <% end %>
                    </li>
                    <br>
                    <li>
                      <i class="far fa-hand-point-down fa-2x"></i>
                      Confira abaixo as vagas desta empresa
                    </li>
                    <br>
                    <li>
                      <%= link_to "Vamos lá",
                        company_path(company),
                        class: "btn btn-lg btn-block btn-outline-danger" %>
                    </li>
                  </ul>
                </div>
              </div>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="container" align="center">
  <h2>Ou escolha uma categoria.</h2>

  <p>
    Não encontrou nenhuma, basta cadastrar, ou confira as <strong>vagas por categoria</strong>
  </p>

  <%= link_to 'Criar Categoria', new_category_path, class: "btn btn-info" %>
  <br><br>

  <div><i class="far fa-grin-beam fa-4x"></i></i></div>
  <br>
  <p><strong>Clique</strong> em uma <strong>categoria</strong> para conferir as vagas</p>
  <br><br>

  <% unless @categories.exists? %>
  <div class="alert alert-warning" role="alert" align="center">
    <i class="far fa-frown"></i> Nenhuma categoria cadastrada
  </div>
  <% else %>
  <% @categories.each do |category| %>
    <%= link_to category.name, category_path(category), class: "btn btn-outline-success" %>
  <% end %>
  <% end %>
</div>

<br>

<footer class="footer">
  <div class="footer-copyright text-center text-black-50 py-3">2018:
    <a class="dark-grey-text" href="http://diegonoronha.com.br/" target="_blank"> Feito com o <i class="fa fa-heart"></i> Diego Noronha</a>
  </div>
</footer>

app/views/jobs/_form.html.erb
  <div class="card">
    <% if current_page?(new_job_path) %>
    <div class="card-header">
      <strong>Criar nova vaga</strong>
    </div>
    <% else %>
    <div class="card-header">
      <strong>Editar vaga</strong>
    </div>
    <% end %>

    <div class="card-body" align="center">
        <%= form_for @job do |f| %>
          <div class="row col-md-6 mb-3">
            <strong>
      				<%= f.label :title do %>
      				<i class="fas fa-clipboard-list"></i>
      				Nome
      				<% end %>
      			</strong>
            <%= f.text_field :title, class:"form-control", required: true, autofocus:true %>
          </div>
          <div class="row col-md-6 mb-3">
            <strong>
      				<%= f.label :location do %>
      				<i class="fas fa-map-marker-alt"></i>
      				Localização
      				<% end %>
      			</strong>
            <%= f.text_field :location, class:"form-control", required: true %>
          </div>
          <div class="row col-md-6 mb-3">
            <strong>
      				<%= f.label :category_id do %>
      				<i class="fas fa-tags"></i>
      				Categoria
      				<% end %>
      			</strong>
            <%= f.select :category_id,
              options_from_collection_for_select(Category.order(:name).all,
              :id, :name, @job.category_id), {:include_blank => 'Escolha a categoria'},
              { class: 'form-control', style: 'text-transform: uppercase'} %>
          </div>
          <div class="row col-md-6 mb-3">
            <strong>
      				<%= f.label :company_id do %>
      				<i class="fas fa-building"></i>
      				Empresa
      				<% end %>
      			</strong>
            <%= f.select :company_id,
              options_from_collection_for_select(Company.order(:name).all,
              :id, :name, @job.company_id), {:include_blank => 'Escolha a empresa'},
              {class: 'form-control', style: 'text-transform: uppercase'} %>
          </div>
          <div class="row col-md-6 mb-3">
            <strong>
      				<%= f.label :description do %>
      				<i class="fas fa-info-circle"></i>
      				Descrição
      				<% end %>
      			</strong>
            <%= f.text_area :description, size: "60x5", class: "form-control", required: true %>
          </div>
          <div class="row col-md-6 mb-3">
            <%= f.check_box :featured %>
            <%= f.label :featured, "Vaga em destaque?", class: "form-check-label" %>
          </div>

          <% if @job.new_record?  %>
          <div class="col-md-6 mb-3">
            <%= button_tag type: 'submit', class: "form-control btn btn-success" do %>
              <i class="fa fa-plus"></i>
              CRIAR
            <% end %><br><br>
          </div>
          <% else %>
            <div class="col-md-6 mb-3">
              <%= button_tag type: 'submit', class: "form-control btn btn-warning" do %>
                <i class="fa fa-edit"></i>
                ATUALIZAR VAGA
              <% end %><br><br>
            </div>
          <% end %>

          <%= link_to root_path, class: 'btn btn-primary' do %>
            <i class="fa fa-arrow-left"></i>
            VOLTAR
          <% end %>
        <% end %>
    </div>
  </div>

app/views/jobs/_job.html.erb
<div class="col-md-4">
  <div class="card-deck mb-3 text-center">
    <div class="card mb-4 box-shadow">
      <div class="card-header">
      <h4 class="my-0 font-weight-normal"><%= job.title %></h4>
      </div>
      <div class="card-body">
        <h3 class="card-title pricing-card-title"><small class="text-muted"><i class="fas fa-clipboard-list"></i> <%= job.description %></small></h3>
        <ul class="list-unstyled mt-3 mb-4">
          <li><%= job.location %></li>
          <% if job.recent? %>
            <li>Vaga recente: <%= person_date job.created_at %></li>
          <% else %>
            <li>Vaga com mais de 5 dias: <%= person_date job_created_at %></li>
          <% end %>
            <li>Categoria: <%= job.category.name %></li>
            <li>Empresa: <%= job.company.name %></li>
          <% if job.featured? %>
          <li><i class="fa fa-star fa-2x text-warning"></i></li>
          <% else  %>
          <li><i class="fa fa-briefcase fa-2x text-primary"></i></li>
          <% end %>
        </ul>
        <%= link_to job_path(job), class: "btn btn-outline-success" do %>
          <i class="fas fa-binoculars"></i>
          VER DETALHES
        <% end %><br>
        <br>
        <%= link_to edit_job_path(job), class: "btn btn-outline-warning" do %>
          <i class="fa fa-edit"></i>
          EDITAR
        <% end %>
        <%= link_to job_path(job), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Você tem certeza que deseja excluir essa vaga? :|" } do %>
          <i class="far fa-trash-alt"></i>
          DELETAR
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/jobs/edit.html.erb
<%= render partial: 'form', locals: {submit_button: 'Atualizar Vaga'} %>

app/views/jobs/new.html.erb
<%= render partial: 'form', locals: {submit_button: 'CRIAR'} %>

app/views/jobs/show.html.erb
<div class="card">
  <div class="card-header bg-default">
    <strong class="">Detalhes da vaga</strong>
  </div>
  <div class="card-body" align="center">
    <p>Título: </p><h1><%= @job.title %></h1>

    <hr>

    <strong>Descrição:</strong>  <%= @job.description %><br><br>
    <strong>Localização:</strong> <%= @job.location %><br><br>
    <strong>Criado em:</strong> <%= person_date @job.created_at %><br><br>
    <strong>Empresa:</strong> <%= @job.company.name %><br><br>
    <strong>Categoria:</strong> <%= @job.category.name %><br><br>
    <% if @job.featured == true %>
    <strong>Vaga em destaque:</strong><br>
      <i class=" fa fa-star fa-2x text-warning" ></i>
      <br><br>
    <% end %>
    <%= link_to root_path, class: "btn btn-primary " do %>
      <i class="fa fa-arrow-left"></i>
      VOLTAR
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="pt-br">
  <head>
    <title>Job GO! Encontre e cadastre o seu Job</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="shortcut icon" type="image/png" href="favicon.ico"/>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <%= link_to "Job GO!", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'Criar vaga', new_job_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Criar empresa', new_company_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Criar categoria', new_category_path, class: "nav-link" %>
            </li>
          </ul>
            <a href="http://diegonoronha.com.br" target="_blank"><button class="btn btn-success">Blog</button></a>
        </div>
      </div>
    </nav>

    <div class="container">
      <br>
      <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>  fade show" role="alert" data-dismiss="alert" align="center" id="danger-alert">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Sair">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% end %>
      <%= yield %>
    </div>
    <br>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>